// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBi1JJQ-CgrG5Bb8lkrNq5haiIgkttrsq4',
    appId: '1:1050194246861:web:4405af3eda4b033f023d84',
    messagingSenderId: '1050194246861',
    projectId: 'insee-ab946',
    authDomain: 'insee-ab946.firebaseapp.com',
    databaseURL: 'https://insee-ab946-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'insee-ab946.appspot.com',
    measurementId: 'G-8QY5FT0900',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAD1oIkNbS8OwT0vprJ1BsPwsiuFxwkbyM',
    appId: '1:1050194246861:android:eb7ce8846e2e173f023d84',
    messagingSenderId: '1050194246861',
    projectId: 'insee-ab946',
    databaseURL: 'https://insee-ab946-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'insee-ab946.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJ3-Qiv3H9Nhjt-KeRqfPQFlXJ4oKNLEk',
    appId: '1:1050194246861:ios:2c1158ddb2beea1e023d84',
    messagingSenderId: '1050194246861',
    projectId: 'insee-ab946',
    databaseURL: 'https://insee-ab946-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'insee-ab946.appspot.com',
    iosClientId: '1050194246861-u48m4v8pferj1vadln8tlg6cp2grsebv.apps.googleusercontent.com',
    iosBundleId: 'com.example.cycleTime',
  );
}
